export const alias = new Map<string, string>([
	['icd10', 'http://hl7.org/fhir/sid/icd-10'],
	['icd10gm', 'http://fhir.de/CodeSystem/dimdi/icd-10-gm'],
	['loinc', 'http://loinc.org'],
	['SampleMaterialType', 'https://fhir.bbmri.de/CodeSystem/SampleMaterialType'], //specimentype
	['StorageTemperature', 'https://fhir.bbmri.de/CodeSystem/StorageTemperature'],
	['FastingStatus', 'http://terminology.hl7.org/CodeSystem/v2-0916'],
	['SmokingStatus', 'http://hl7.org/fhir/uv/ips/ValueSet/current-smoking-status-uv-ips']
]);

export const cqltemplate = new Map<string, string>([
	['gender', "Patient.gender = '{{C}}'"],
	[
		'conditionSampleDiagnosis',
		"((exists[Condition: Code '{{C}}' from {{A1}}]) or (exists[Condition: Code '{{C}}' from {{A2}}])) or (exists from [Specimen] S where (S.extension.where(url='https://fhir.bbmri.de/StructureDefinition/SampleDiagnosis').value.coding.code contains '{{C}}'))"
	],
	['conditionValue', "exists [Condition: Code '{{C}}' from {{A1}}]"],
	[
		'conditionRangeDate',
		'exists from [Condition] C\nwhere FHIRHelpers.ToDateTime(C.onset) between {{D1}} and {{D2}}'
	],
	[
		'conditionRangeAge',
		'exists from [Condition] C\nwhere AgeInYearsAt(FHIRHelpers.ToDateTime(C.onset)) between Ceiling({{D1}}) and Ceiling({{D2}})'
	],
	[
		'conditionGreaterThanAge',
		'exists from [Condition] C\nwhere AgeInYearsAt(FHIRHelpers.ToDateTime(C.onset)) between Ceiling({{D1}}) and Ceiling({{D2}})'
	],
	['age', 'AgeInYears() between Ceiling({{D1}}) and Ceiling({{D2}})'],
	[
		'observation',
		"exists from [Observation: Code '{{K}}' from {{A1}}] O\nwhere O.value.coding.code contains '{{C}}'"
	],
	[
		'observationRange',
		"exists from [Observation: Code '{{K}}' from {{A1}}] O\nwhere O.value between {{D1}} and {{D2}}"
	],
	[
		'observationBodyWeight',
		"exists from [Observation: Code '{{K}}' from {{A1}}] O\nwhere ((O.value as Quantity) < {{D1}} 'kg' and (O.value as Quantity) > {{D2}} 'kg')"
	],
	[
		'observationBMI',
		"exists from [Observation: Code '{{K}}' from {{A1}}] O\nwhere ((O.value as Quantity) < {{D1}} 'kg/m2' and (O.value as Quantity) > {{D2}} 'kg/m2')"
	],
	['hasSpecimen', 'exists [Specimen]'],
	['specimen', "exists [Specimen: Code '{{C}}' from {{A1}}]"],
	['retrieveSpecimenByType', "(S.type.coding.code contains '{{C}}')"],
	[
		'retrieveSpecimenByTemperature',
		"(S.extension.where(url='https://fhir.bbmri.de/StructureDefinition/StorageTemperature').value.coding.code contains '{{C}}')"
	],
	[
		'retrieveSpecimenBySamplingDate',
		'(FHIRHelpers.ToDateTime(S.collection.collected) between {{D1}} and {{D2}})'
	],
	[
		'retrieveSpecimenByFastingStatus',
		"(S.collection.fastingStatus.coding.code contains '{{C}}')"
	],
	[
		'samplingDate',
		'exists from [Specimen] S\nwhere FHIRHelpers.ToDateTime(S.collection.collected) between {{D1}} and {{D2}}'
	],
	[
		'fastingStatus',
		"exists from [Specimen] S\nwhere S.collection.fastingStatus.coding.code contains '{{C}}'"
	],
	[
		'storageTemperature',
		"exists from [Specimen] S where (S.extension.where(url='https://fhir.bbmri.de/StructureDefinition/StorageTemperature').value.coding contains Code '{{C}}' from {{A1}})"
	],
	//neu
	['AFFILIATION_TTU_TI', "exists from [Observation: Code '{{C}}']"],
	['AFFILATION_STUDY', "exists from [Observation: Code '{{C}}']"],
	['ORG_UNIT', "exists from [Observation: Code '{{C}}']"],
	['CONSENT_GENERAL', "exists from [Observation: Code '{{C}}']"],
	['CONSENT_SIGN', "exists from [Observation: Code '{{C}}']"],
	['CONSENT_RESTRICTION', "exists from [Observation: Code '{{C}}']"],
	['CONSENT_SIGNDATE', "exists from [Observation: Code '{{C}}']"],
	['CONSENT_VERSDATE', "exists from [Observation: Code '{{C}}']"],
	['WITHDRAWAL', "exists from [Observation: Code '{{C}}']"],
	['WITHDRAWAL_DATE', "exists from [Observation: Code '{{C}}']"],
	['PARTICIPANT_TYPE', "exists from [Observation: Code '{{C}}']"],
	['INCLUSION_REASON', "exists from [Observation: Code '{{C}}']"],
	['STUDY_ENDPOINT', "exists from [Observation: Code '{{C}}']"],
	['DATE_OF_DEATH', "exists from [Observation: Code '{{C}}']"],
	['AGE_AT_INCLUSION', "exists from [Observation: Code '{{C}}']"],
	['SEX', "exists from [Observation: Code '{{C}}']"],
	['SEX_OTHER', "exists from [Observation: Code '{{C}}']"],
	['VISIT_START', "exists from [Observation: Code '{{C}}']"],
	['VISIT_TYPE', "exists from [Observation: Code '{{C}}']"],
	['VISIT_TYPE_OTHER', "exists from [Observation: Code '{{C}}']"],
	['VISIT_TYPE_NUMBER', "exists from [Observation: Code '{{C}}']"],
	['VISIT_TYPE_UNIT', "exists from [Observation: Code '{{C}}']"],
	['TRANSPLANTATION_EXDATE', "exists from [Observation: Code '{{C}}']"],
	['TRANSPLANTATION', "exists from [Observation: Code '{{C}}']"],
	['TRANSPLANTATION_AMOUNT_OF_TRANSPLANS', "exists from [Observation: Code '{{C}}']"],
	['TRANSPLANTATION_ORGAN', "exists from [Observation: Code '{{C}}']"],
	['SMOKING_STATUS', "exists from [Observation: Code '{{C}}']"],
	['WEIGHT', "exists from [Observation: Code '{{C}}']"],
	['HEIGHT', "exists from [Observation: Code '{{C}}']"],
	['CARDVASC_HT', "exists from [Observation: Code '{{C}}']"],
	['CARDVASC_HT_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['CARDVASC_CHD', "exists from [Observation: Code '{{C}}']"],
	['CARDVASC_CHD_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['CARDVASC', "exists from [Observation: Code '{{C}}']"],
	['CHR_LUNG', "exists from [Observation: Code '{{C}}']"],
	['CHR_LUNG_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['CHR_KIDNEYD', "exists from [Observation: Code '{{C}}']"],
	['CHR_LIVERDIS', "exists from [Observation: Code '{{C}}']"],
	['RHEU_IMMU', "exists from [Observation: Code '{{C}}']"],
	['CHR_MYOBAKT', "exists from [Observation: Code '{{C}}']"],
	['CHR_MYOBAKT_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['MALARIA', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_HIV', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_HIV_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_HBV', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_HBV_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_HCV', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_HCV_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_OTHER', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_OTHER_INFO', "exists from [Observation: Code '{{C}}']"],
	['CHR_VIRUS_OTHER_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['NEURO', "exists from [Observation: Code '{{C}}']"],
	['NEURO_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['DIABETES', "exists from [Observation: Code '{{C}}']"],
	['DIABETES_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['TUMOR_ACTIVE', "exists from [Observation: Code '{{C}}']"],
	['TUMOR_MORPHOLOGY', "exists from [Observation: Code '{{C}}']"],
	['TUMOR_DIAG_YEAR', "exists from [Observation: Code '{{C}}']"],
	['CLINICAL_INFECTION', "exists from [Observation: Code '{{C}}']"],
	['CLINICAL_INFECTION_DATE', "exists from [Observation: Code '{{C}}']"],
	['PTG_CULT_DATE', "exists from [Observation: Code '{{C}}']"],
	['VITAL_RR', "exists from [Observation: Code '{{C}}']"],
	['VITAL_TEMP', "exists from [Observation: Code '{{C}}']"],
	['MEDS', "exists from [Observation: Code '{{C}}']"],
	['MEDS_IMMUNSUPPR', "exists from [Observation: Code '{{C}}']"],
	['MEDS_CORTISONE', "exists from [Observation: Code '{{C}}']"],
	['MEDS_ANTIHYPERTENSIVES', "exists from [Observation: Code '{{C}}']"],
	['MEDS_INSULIN', "exists from [Observation: Code '{{C}}']"],
	['MEDS_ASTHMA', "exists from [Observation: Code '{{C}}']"],
	['MEDS_ANTIHISTAMINES', "exists from [Observation: Code '{{C}}']"],
	['MEDS_ANTICOAGULANT', "exists from [Observation: Code '{{C}}']"],
	['MEDS_CHEMO', "exists from [Observation: Code '{{C}}']"],
	['MEDS_ANTIINFECTIVES', "exists from [Observation: Code '{{C}}']"],
	['BIOSAMPLE_RETRIEVAL', "exists from [Observation: Code '{{C}}']"],
	['BIOSAMPLE_RETRIEVAL_DATE', "exists from [Observation: Code '{{C}}']"],
	['BIOSAMPLE_RETRIEVAL_TIME', "exists from [Observation: Code '{{C}}']"],
	['BIOSAMPLE_RETRIEVAL_LOCATION', "exists from [Observation: Code '{{C}}']"],
	['BIOSAMPLE_TYPE', "exists from [Specimen: Type '{{C}}']"],
	['BIOSAMPLE_AMOUNT', "exists from [Observation: Code '{{C}}']"],
	['BIOSAMPLE_AMOUNT_UNIT', "exists from [Observation: Code '{{C}}']"],
	['BIO_SAMPLING_DATE', "exists from [Observation: Code '{{C}}']"],
	['INFECTION_ACUTE', "exists from [Observation: Code '{{C}}']"]
]);

export const criterionMap = new Map<string, { type: string; alias?: string[] }>([
	['gender', { type: 'gender' }],
	['diagnosis', { type: 'conditionSampleDiagnosis', alias: ['icd10', 'icd10gm'] }],
	['29463-7', { type: 'observationBodyWeight', alias: ['loinc'] }], //Body weight
	['39156-5', { type: 'observationBMI', alias: ['loinc'] }], //BMI
	['72166-2', { type: 'observation', alias: ['loinc'] }], //Smoking habit
	['donor_age', { type: 'age' }],
	['date_of_diagnosis', { type: 'conditionRangeDate' }],
	['sample_kind', { type: 'specimen', alias: ['SampleMaterialType'] }],
	['storage_temperature', { type: 'storageTemperature', alias: ['StorageTemperature'] }],
	['pat_with_samples', { type: 'hasSpecimen' }],
	['diagnosis_age_donor', { type: 'conditionRangeAge' }],
	['fasting_status', { type: 'fastingStatus', alias: ['FastingStatus'] }],
	['sampling_date', { type: 'samplingDate' }],
	//neu
	['AFFILIATION_TTU_TI', { type: 'AFFILIATION_TTU_TI' }],
	['AFFILATION_STUDY', { type: 'AFFILATION_STUDY' }],
	['ORG_UNIT', { type: 'ORG_UNIT' }],
	['CONSENT_GENERAL', { type: 'CONSENT_GENERAL' }],
	['CONSENT_SIGN', { type: 'CONSENT_SIGN' }],
	['CONSENT_RESTRICTION', { type: 'CONSENT_RESTRICTION' }],
	['CONSENT_SIGNDATE', { type: 'CONSENT_SIGNDATE' }],
	['CONSENT_VERSDATE', { type: 'CONSENT_VERSDATE' }],
	['WITHDRAWAL', { type: 'WITHDRAWAL' }],
	['WITHDRAWAL_DATE', { type: 'WITHDRAWAL_DATE' }],
	['PARTICIPANT_TYPE', { type: 'PARTICIPANT_TYPE' }],
	['INCLUSION_REASON', { type: 'INCLUSION_REASON' }],
	['STUDY_ENDPOINT', { type: 'STUDY_ENDPOINT' }],
	['DATE_OF_DEATH', { type: 'DATE_OF_DEATH' }],
	['AGE_AT_INCLUSION', { type: 'AGE_AT_INCLUSION' }],
	['SEX', { type: 'SEX' }],
	['SEX_OTHER', { type: 'SEX_OTHER' }],
	['VISIT_START', { type: 'VISIT_START' }],
	['VISIT_TYPE', { type: 'VISIT_TYPE' }],
	['VISIT_TYPE_OTHER', { type: 'VISIT_TYPE_OTHER' }],
	['VISIT_TYPE_NUMBER', { type: 'VISIT_TYPE_NUMBER' }],
	['VISIT_TYPE_UNIT', { type: 'VISIT_TYPE_UNIT' }],
	['TRANSPLANTATION_EXDATE', { type: 'TRANSPLANTATION_EXDATE' }],
	['TRANSPLANTATION', { type: 'TRANSPLANTATION' }],
	[
		'TRANSPLANTATION_AMOUNT_OF_TRANSPLANS',
		{ type: 'TRANSPLANTATION_AMOUNT_OF_TRANSPLANS' }
	],
	['TRANSPLANTATION_ORGAN', { type: 'TRANSPLANTATION_ORGAN' }],
	['SMOKING_STATUS', { type: 'SMOKING_STATUS' }],
	['WEIGHT', { type: 'WEIGHT' }],
	['HEIGHT', { type: 'HEIGHT' }],
	['CARDVASC_HT', { type: 'CARDVASC_HT' }],
	['CARDVASC_HT_DIAG_YEAR', { type: 'CARDVASC_HT_DIAG_YEAR' }],
	['CARDVASC_CHD', { type: 'CARDVASC_CHD' }],
	['CARDVASC_CHD_DIAG_YEAR', { type: 'CARDVASC_CHD_DIAG_YEAR' }],
	['CARDVASC', { type: 'CARDVASC' }],
	['CHR_LUNG', { type: 'CHR_LUNG' }],
	['CHR_LUNG_DIAG_YEAR', { type: 'CHR_LUNG_DIAG_YEAR' }],
	['CHR_KIDNEYD', { type: 'CHR_KIDNEYD' }],
	['CHR_LIVERDIS', { type: 'CHR_LIVERDIS' }],
	['RHEU_IMMU', { type: 'RHEU_IMMU' }],
	['CHR_MYOBAKT', { type: 'CHR_MYOBAKT' }],
	['CHR_MYOBAKT_DIAG_YEAR', { type: 'CHR_MYOBAKT_DIAG_YEAR' }],
	['MALARIA', { type: 'MALARIA' }],
	['CHR_VIRUS_HIV', { type: 'CHR_VIRUS_HIV' }],
	['CHR_VIRUS_HIV_DIAG_YEAR', { type: 'CHR_VIRUS_HIV_DIAG_YEAR' }],
	['CHR_VIRUS_HBV', { type: 'CHR_VIRUS_HBV' }],
	['CHR_VIRUS_HBV_DIAG_YEAR', { type: 'CHR_VIRUS_HBV_DIAG_YEAR' }],
	['CHR_VIRUS_HCV', { type: 'CHR_VIRUS_HCV' }],
	['CHR_VIRUS_HCV_DIAG_YEAR', { type: 'CHR_VIRUS_HCV_DIAG_YEAR' }],
	['CHR_VIRUS_OTHER', { type: 'CHR_VIRUS_OTHER' }],
	['CHR_VIRUS_OTHER_INFO', { type: 'CHR_VIRUS_OTHER_INFO' }],
	['CHR_VIRUS_OTHER_DIAG_YEAR', { type: 'CHR_VIRUS_OTHER_DIAG_YEAR' }],
	['NEURO', { type: 'NEURO' }],
	['NEURO_DIAG_YEAR', { type: 'NEURO_DIAG_YEAR' }],
	['DIABETES', { type: 'DIABETES' }],
	['DIABETES_DIAG_YEAR', { type: 'DIABETES_DIAG_YEAR' }],
	['TUMOR_ACTIVE', { type: 'TUMOR_ACTIVE' }],
	['TUMOR_MORPHOLOGY', { type: 'TUMOR_MORPHOLOGY' }],
	['TUMOR_DIAG_YEAR', { type: 'TUMOR_DIAG_YEAR' }],
	['CLINICAL_INFECTION', { type: 'CLINICAL_INFECTION' }],
	['CLINICAL_INFECTION_DATE', { type: 'CLINICAL_INFECTION_DATE' }],
	['PTG_CULT_DATE', { type: 'PTG_CULT_DATE' }],
	['VITAL_RR', { type: 'VITAL_RR' }],
	['VITAL_TEMP', { type: 'VITAL_TEMP' }],
	['MEDS', { type: 'MEDS' }],
	['MEDS_IMMUNSUPPR', { type: 'MEDS_IMMUNSUPPR' }],
	['MEDS_CORTISONE', { type: 'MEDS_CORTISONE' }],
	['MEDS_ANTIHYPERTENSIVES', { type: 'MEDS_ANTIHYPERTENSIVES' }],
	['MEDS_INSULIN', { type: 'MEDS_INSULIN' }],
	['MEDS_ASTHMA', { type: 'MEDS_ASTHMA' }],
	['MEDS_ANTIHISTAMINES', { type: 'MEDS_ANTIHISTAMINES' }],
	['MEDS_ANTICOAGULANT', { type: 'MEDS_ANTICOAGULANT' }],
	['MEDS_CHEMO', { type: 'MEDS_CHEMO' }],
	['MEDS_ANTIINFECTIVES', { type: 'MEDS_ANTIINFECTIVES' }],
	['BIOSAMPLE_RETRIEVAL', { type: 'BIOSAMPLE_RETRIEVAL' }],
	['BIOSAMPLE_RETRIEVAL_DATE', { type: 'BIOSAMPLE_RETRIEVAL_DATE' }],
	['BIOSAMPLE_RETRIEVAL_TIME', { type: 'BIOSAMPLE_RETRIEVAL_TIME' }],
	['BIOSAMPLE_RETRIEVAL_LOCATION', { type: 'BIOSAMPLE_RETRIEVAL_LOCATION' }],
	['BIOSAMPLE_TYPE', { type: 'BIOSAMPLE_TYPE' }],
	['BIOSAMPLE_AMOUNT', { type: 'BIOSAMPLE_AMOUNT' }],
	['BIOSAMPLE_AMOUNT_UNIT', { type: 'BIOSAMPLE_AMOUNT_UNIT' }],
	['BIO_SAMPLING_DATE', { type: 'BIO_SAMPLING_DATE' }],
	['INFECTION_ACUTE', { type: 'INFECTION_ACUTE' }]
]);
